name: eSoap
favicon: null
layout_spectrum: 0.3297461417969316
typography_spectrum: 0.589482007548213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6150113840121776
  lightness: 0.15973685099743307
  saturation: 0.8995689896401018
  rhythmicContrast: 0.825940317241475
purpose: []
